source "https://github.com/retro-labs/specs-ios-swift.git"
source "https://github.com/CocoaPods/Specs.git"

use_frameworks!

ENV['PWManager_LocalPath'] = 'true'

platform :ios, '13.0'

target 'PWManager_Example' do
  pod 'PWManager/normal', :path => '../'
  pod 'PWManager/u8enjsbh', :path => '../'
  pod 'PWManager/template', :path => '../'
  target 'PWManager_Tests' do
    inherit! :search_paths

    
  end
end
